import { QuizItem, VocabDataDef } from "../Objects/quiz";

export default {
    name:"Japanese",
    termsNames:["Kana","Kanji","English","Romaji"],
    topicsNames:["Topic 1","Topic 2","Topic 3","Topic 4","Topic 5","Topic 6","Topic 7","Topic 8","Topic 9","Topic 10","Topic 11","Topic 12","Topic 13","Topic 14","Topic 15","Topic 16","Topic 17","Topic 18","Topic 19","Topic 20","Topic 21","Topic 22","Topic 23","Topic 24","Topic 25","Topic 26","Topic 27","Topic 28","Topic 29","Topic 30","Topic 31","Topic 32","Topic 33","Topic 34","Topic 35","Topic 36","Topic 37","Topic 38"],
    topics:[
        [{"terms": ["にんげん", "人間", "human", "ningen"]},
            {"terms": ["じんるい", "人類", "humanity", "jinrui"]},
            {"terms": ["ひと", "人", "person", "hito"]},
            {"terms": ["おとこ", "男", "male", "otoko"]},
            {"terms": ["おとこのひと", "男の人", "man", "otokonohito"]},
            {"terms": ["おとこのこ", "男の子", "boy", "otokonoko"]},
            {"terms": ["おんな", "女", "female", "onna"]},
            {"terms": ["おんなのひと", "女の人", "woman", "onnanohito"]},
            {"terms": ["おんなのこ", "女の子", "girl", "onnanoko"]},
            {"terms": ["あかちゃん", "赤ちゃん", "baby", "akachan"]},
            {"terms": ["わかもの", "若者", "youth, young person", "wakamono"]},
            {"terms": ["わたし", "私", "I, myself", "watashi"]},
            {"terms": ["わたくし", "私", "I, myself", "watakushi"]},
            {"terms": ["ぼく", "僕", "I, myself", "boku"]},
            {"terms": ["おれ","俺", "I, myself", "ore"]},
            {"terms": ["あたし", "私", "I, myself", "atashi"]},
            {"terms": ["しょうじょ", "少女", "girl", "shoujo"]},
            {"terms": ["しょうねん", "少年", "boy", "shounen"]},
            {"terms": ["いしゃ", "医者", "doctor", "isha"]},
            {"terms": ["かんごし", "看護師", "nurse", "kangoshi"]},
            {"terms": ["かんごふ", "看護婦", "female nurse", "kangofu"]},
            {"terms": ["はいしゃ", "歯医者", "dentist", "ha-isha"]},
            {"terms": ["しかい", "歯科医", "dentist", "shikai"]},
            {"terms": ["せいじか", "政治家", "politician", "seijika"]},
            {"terms": ["べんごし", "弁護士", "lawyer", "bengoshi"]},
            {"terms": ["しょうぼうし","消防士", "firefighter", "shouboushi"]},
            {"terms": ["けいさつかん", "警察官", "police officer", "keisatsukan"]},
            {"terms": ["へいし", "兵士", "soldier", "heishi"]},
            {"terms": ["けんちくか", "建築家", "architect", "kenchikuka"]},
            {"terms": ["せんせい", "先生", "teacher", "sensei"]},
            {"terms": ["きょうし", "教師", "academic teacher", "kyoushi"]},
            {"terms": ["かしゅ", "歌手", "singer", "kashu"]},
            {"terms": ["エンジニア", "エンジニア", "engineer", "enjinia"]}
        ],
    
        [
            {"terms": ["あし", "足、 脚", "foot, leg", "ashi"]},
            {"terms": ["かかと", "踵", "heel", "kakato"]},
            {"terms": ["すね", "脛", "shin", "sune"]},
            {"terms": ["ひざ", "膝", "knee", "hiza"]},
            {"terms": ["もも", "腿", "thigh", "momo"]},
            {"terms": ["あたま", "頭", "head", "atama"]},
            {"terms": ["かお", "顔", "face", "kao"]},
            {"terms": ["くち", "口", "mouth", "kuchi"]},
            {"terms": ["くちびる", "唇", "lips", "kuchibiru"]},
            {"terms": ["は", "歯", "tooth", "ha"]},
            {"terms": ["はな", "鼻", "nose", "hana"]},
            {"terms": ["め", "目", "eye", "me"]},
            {"terms": ["ひげ", "髭", "moustache; beard", "hige"]},
            {"terms": ["かみ", "髪", "hair", "kami"]},
            {"terms": ["みみ", "耳", "ear", "mimi"]},
            {"terms": ["い", "胃", "stomach", "i"]},
            {"terms": ["うで", "腕", "arm", "ude"]},
            {"terms": ["ひじ", "肘", "elbow", "hiji"]},
            {"terms": ["かた", "肩", "shoulder", "kata"]},
            {"terms": ["つめ", "爪", "nail", "tsume"]},
            {"terms": ["て", "手", "hand", "te"]},
            {"terms": ["てくび", "手首", "wrist", "tekubi"]},
            {"terms": ["てのひら", "掌、 手の平", "palm of hand", "te-no-hira"]},
            {"terms": ["ゆび", "指", "finger; toe", "yubi"]},
            {"terms": ["しり", "尻", "buttocks", "shiri"]},
            {"terms": ["おなか", "お腹", "abdomen", "o-naka"]},
            {"terms": ["はら", "腹", "abdomen", "hara"]},
            {"terms": ["かんぞう", "肝臓", "liver", "kanzō"]},
            {"terms": ["きも", "肝", "liver", "kimo"]},
            {"terms": ["きんにく", "筋肉", "muscle", "kinniku"]},
            {"terms": ["くび", "首", "neck", "kubi"]},
            {"terms": ["こころ", "心", "heart [as in feelings]", "kokoro"]},
            {"terms": ["こし", "腰", "waist, hip", "koshi"]},
            {"terms": ["しんぞう", "心臓", "heart", "shinzō"]},
            {"terms": ["せなか", "背中", "back", "senaka"]},
            {"terms": ["ち", "血", "blood", "chi"]},
            {"terms": ["にく", "肉", "meat", "niku"]},
            {"terms": ["はだ", "肌、膚", "skin", "hada"]},
            {"terms": ["ひふ", "皮膚", "skin", "hifu"]},
            {"terms": ["ほね", "骨", "bone", "hone"]},
            {"terms": ["むね", "胸", "chest", "mune"]},
            {"terms": ["かぜ", "風邪", "cold [illness]", "kaze"]},
            {"terms": ["げり", "下痢", "diarrhea", "geri"]},
            {"terms": ["びょうき", "病気", "illness", "byōki"]}
        ],
    
        [
            {"terms": ["かぞく", "家族", "family", "kazoku"]},
            {"terms": ["りょうしん", "両親", "parents", "ryoushin"]},
            {"terms": ["こども", "子供", "children, child", "kodomo"]},
            {"terms": ["ちち", "父", "father", "chichi, otou-san"]},
            {"terms": ["はは", "母", "mother", "haha, okaa-san"]},
            {"terms": ["つま", "妻", "wife", "tsuma"]},
            {"terms": ["おっと", "夫", "husband", "otto"]},
            {"terms": ["あに", "兄", "older brother", "ani, onī-san"]},
            {"terms": ["あね", "姉", "older sister", "ane, onē-san"]},
            {"terms": ["おとうと", "弟", "younger brother", "otōto"]},
            {"terms": ["いもうと", "妹", "younger sister", "imōto"]},
            {"terms": ["きょうだい", "兄弟", "brothers", "siblings, kyōdai"]},
            {"terms": ["しまい", "姉妹", "sisters", "shimai"]},
            {"terms": ["そふ", "祖父", "grandfather", "sofu, ojii-san"]},
            {"terms": ["そぼ", "祖母", "grandmother", "sobo, obaa-san"]},
            {"terms": ["まご", "孫", "grandchild", "mago"]},
            {"terms": ["おじ", "伯父、叔父", "uncle", "oji, oji-san"]},
            {"terms": ["おば", "伯母、叔母", "aunt", "oba, oba-san"]},
            {"terms": ["いとこ", "従兄弟", "cousin (male)", "itoko"]},
            {"terms": ["いとこ", "従姉妹", "cousin (female)", "itoko"]},
            {"terms": ["じゅうけい、いとこ", "従兄", "cousin (elder male)", "jūkei, itoko"]},
            {"terms": ["じゅうし、いとこ", "従姉", "cousin (elder female)", "jūshi, itoko"]},
            {"terms": ["じゅうまい、いとこ", "従妹", "cousin (younger female)", "jūmai, itoko"]},
            {"terms": ["じゅうてい、いとこ", "従弟", "cousin (younger male)", "jūtei, itoko"]},
            {"terms": ["めい", "姪", "niece", "mei"]},
            {"terms": ["おい", "甥", "nephew", "oi"]}
        ],
    
        [
            {"terms": ["いきもの", "生き物", "living creatures", "ikimono"]},
            {"terms": ["ばけもの", "化け物", "monster", "bakemono"]},
            {"terms": ["どうぶつ", "動物", "animal", "dōbutsu"]},
            {"terms": ["チーター", "", "cheetah", "chītā"]},
            {"terms": ["いぬ", "犬", "dog", "inu"]},
            {"terms": ["ねこ", "猫", "cat", "neko"]},
            {"terms": ["うし", "牛", "cow", "ushi"]},
            {"terms": ["ぶた", "豚", "pig", "buta"]},
            {"terms": ["うま", "馬", "horse", "uma"]},
            {"terms": ["ひつじ", "羊", "sheep", "hitsuji"]},
            {"terms": ["さる", "猿", "monkey", "saru"]},
            {"terms": ["ねずみ", "鼠", "mouse, rat", "nezumi"]},
            {"terms": ["とら", "虎", "tiger", "tora"]},
            {"terms": ["オオカミ", "狼", "wolf", "ōkami"]},
            {"terms": ["うさぎ", "兎", "rabbit", "usagi"]},
            {"terms": ["りゅう、 たつ", "竜", "dragon", "ryū, tatsu"]},
            {"terms": ["しか", "鹿", "deer", "shika"]},
            {"terms": ["かえる", "蛙", "frog", "kaeru"]},
            {"terms": ["がま", "蟇", "toad", "gama"]},
            {"terms": ["しし", "獅子", "lion", "shishi"]},
            {"terms": ["キリン", "麒麟", "giraffe", "kirin"]},
            {"terms": ["ぞう", "象", "elephant", "zō"]},
            {"terms": ["とり", "鳥", "bird", "tori"]},
            {"terms": ["にわとり", "鶏", "chicken", "niwatori"]},
            {"terms": ["すずめ", "雀", "sparrow", "suzume"]},
            {"terms": ["からす", "烏、鴉", "crow, raven", "karasu"]},
            {"terms": ["わし", "鷲", "eagle", "washi"]},
            {"terms": ["たか", "鷹", "hawk, falcon", "taka"]},
            {"terms": ["さかな", "魚", "fish", "sakana"]},
            {"terms": ["たい", "鯛", "red snapper", "tai"]},
            {"terms": ["えび", "海老", "shrimp, lobster", "ebi"]},
            {"terms": ["いわし", "鰯", "sardine", "iwashi"]},
            {"terms": ["まぐろ", "鮪", "tuna", "maguro"]},
            {"terms": ["かつお", "鰹", "bonito", "katsuo"]},
            {"terms": ["さんま", "秋刀魚", "pike", "sanma"]},
            {"terms": ["あじ", "鰺", "horse mackerel", "aji"]},
            {"terms": ["さば", "鯖", "mackerel", "saba"]},
            {"terms": ["イカ", "烏賊", "squid", "ika"]},
            {"terms": ["タコ", "蛸、章魚", "octopus", "tako"]},
            {"terms": ["むし", "虫", "insect", "mushi"]},
            {"terms": ["ちょう", "蝶", "butterfly", "chō"]},
            {"terms": ["ガ", "蛾", "moth", "ga"]},
            {"terms": ["せみ", "蝉", "cicada", "semi"]},
            {"terms": ["トンボ", "蜻蛉", "dragonfly", "tonbo"]},
            {"terms": ["バッタ", "飛蝗", "grasshopper", "batta"]},
            {"terms": ["クモ", "蜘蛛", "spider", "kumo"]},
            {"terms": ["ホタル", "蛍", "firefly", "hotaru"]},
            {"terms": ["ハエ", "蝿、蠅", "housefly", "hae"]},
            {"terms": ["カ", "蚊", "mosquito, gnat", "ka"]},
            {"terms": ["ゴキブリ", "蜚蠊", "cockroach", "gokiburi"]},
            {"terms": ["カタツムリ", "蝸牛", "snail", "katatsumuri"]},
            {"terms": ["ナメクジ", "蛞蝓", "slug", "namekuji"]},
            {"terms": ["ミミズ", "蚯蚓", "earthworm", "mimizu"]},
            {"terms": ["かい", "貝", "shellfish", "kai"]},
            {"terms": ["かいがら", "貝殻", "shell", "kaigara"]},
            {"terms": ["トカゲ", "蜥蜴", "lizard", "tokage"]},
            {"terms": ["へび", "蛇", "snake", "hebi"]}
        ],
    
        [
            {"terms": ["しょくぶつ", "植物", "shokubutsu", "plants"]},
            {"terms": ["くさ", "草", "kusa", "grass"]},
            {"terms": ["はな", "花", "hana", "flower"]},
            {"terms": ["み", "実", "mi", "fruit"]},
            {"terms": ["き", "木", "ki", "tree"]},
            {"terms": ["は or はっぱ", "葉、葉っぱ", "ha or happa", "leaf"]},
            {"terms": ["ね or ねっこ", "根、根っ子", "ne or nekko", "root"]},
            {"terms": ["くき", "茎", "kuki", "stem"]},
            {"terms": ["きのこ", "茸", "kinoko", "mushroom"]},
            {"terms": ["きく", "菊", "kiku", "chrysanthemum"]},
            {"terms": ["さくら", "桜", "sakura", "cherry blossom"]},
            {"terms": ["こめ", "米", "uncooked rice", "kome"]},
            {"terms": ["いね", "稲", "rice growing in a field", "ine"]},
            {"terms": ["むぎ", "麦", "wheat, barley, oats", "mugi"]},
            {"terms": ["やさい", "野菜", "vegetable", "yasai"]},
            {"terms": ["くだもの", "果物", "fruit for eating", "kudamono"]},
            {"terms": ["いも", "芋", "potato", "imo"]},
            {"terms": ["まめ", "豆", "beans, peas", "mame"]},
            {"terms": ["だいこん", "大根", "Japanese white radish", "daikon"]},
            {"terms": ["にんじん", "人参", "carrot", "ninjin"]},
            {"terms": ["リンゴ", "林檎", "apple", "ringo"]},
            {"terms": ["ミカン", "蜜柑", "mandarin orange", "mikan"]},
            {"terms": ["バナナ、かんしょう", "甘蕉", "banana", "banana, kanshō"]},
            {"terms": ["ナシ", "梨", "pear", "nashi"]},
            {"terms": ["クリ", "栗", "chestnut tree", "kuri"]},
            {"terms": ["モモ", "桃", "peach", "momo"]},
            {"terms": ["トマト、ばんか", "蕃茄", "tomato", "tomato, banka"]},
            {"terms": ["スイカ", "西瓜", "watermelon", "suika"]}
        ],
    
        [
            {"terms": ["たべもの", "食べ物", "food", "tabemono"]},
            {"terms": ["ちょうしょく", "朝食", "breakfast", "chōshoku, asagohan"]},
            {"terms": ["ひるごはん", "昼御飯", "lunch", "hirugohan"]},
            {"terms": ["ばんごはん", "晩御飯", "supper", "bangohan"]},
            {"terms": ["ごはん", "御飯", "cooked rice or food", "gohan"]},
            {"terms": ["みそ", "味噌", "miso", "miso"]},
            {"terms": ["りょうり", "料理", "cooking", "ryōri"]},
            {"terms": ["サラダ", "サラダ", "salad", "sarada"]},
            {"terms": ["デザート", "デザート", "dessert", "dezāto"]},
            {"terms": ["パン", "パン", "bread", "pan"]},
            {"terms": ["サンドイッチ", "サンドイッチ", "sandwich", "sandoitchi"]},
            {"terms": ["おやつ", "間食", "snack", "oyatsu"]},
            {"terms": ["アイスクリーム", "アイスクリーム", "ice cream", "aisukurīmu"]},
            {"terms": ["のみもの", "飲み物", "drink/beverage", "nomimono"]},
            {"terms": ["ちゃ", "茶", "tea", "cha"]},
            {"terms": ["おちゃ", "お茶", "green tea", "ocha"]},
            {"terms": ["コーヒー", "珈琲", "coffee", "kōhī"]},
            {"terms": ["ぎゅうにゅう", "牛乳", "milk", "gyūnyū"]},
            {"terms": ["みず", "水", "water", "mizu"]},
            {"terms": ["ビール", "ビール", "beer", "bīru"]},
            {"terms": ["ワイン", "ワイン", "wine", "wain"]},
            {"terms": ["さとう", "砂糖", "sugar", "satō"]},
            {"terms": ["しお", "塩", "salt", "shio"]},
            {"terms": ["しょうゆ", "醤油", "soy sauce", "shōyu"]}
        ],
    
        [
            {"terms": ["じかん", "時間", "time", "jikan"]},
            {"terms": ["とき、じ", "時", "~hours", "toki, ji"]},
            {"terms": ["こよみ、カレンダー", "暦", "calendar", "koyomi, karendā"]},
            {"terms": ["ふん", "分", "minute", "fun"]},
            {"terms": ["びょう", "秒", "second", "byō"]},
            {"terms": ["ひ、にち", "日", "day", "hi, nichi"]},
            {"terms": ["つき、げつ", "月", "month", "tsuki, gatsu"]},
            {"terms": ["いちがつ", "一月", "january", "ichigatsu"]},
            {"terms": ["にがつ", "二月", "february", "nigatsu"]},
            {"terms": ["さんがつ", "三月", "march", "sangatsu"]},
            {"terms": ["しがつ", "四月", "april", "shigatsu"]},
            {"terms": ["ごがつ", "五月", "may", "gogatsu"]},
            {"terms": ["ろくがつ", "六月", "june", "rokugatsu"]},
            {"terms": ["しちがつ", "七月", "july", "shichigatsu"]},
            {"terms": ["はちがつ", "八月", "august", "hachigatsu"]},
            {"terms": ["くがつ", "九月", "september", "kugatsu"]},
            {"terms": ["じゅうがつ", "十月", "october", "jūgatsu"]},
            {"terms": ["じゅういちがつ", "十一月", "november", "jūichigatsu"]},
            {"terms": ["じゅうにがつ", "十二月", "december", "jūnigatsu"]},
            {"terms": ["とし、ねん", "年", "year", "toshi, nen"]},
            {"terms": ["きょねん", "去年", "last year", "kyonen"]},
            {"terms": ["ことし", "今年", "this year", "kotoshi"]},
            {"terms": ["らいねん", "来年", "next year", "rainen"]},
            {"terms": ["きのう、さくじつ", "昨日", "yesterday", "kinō, sakujitsu"]},
            {"terms": ["きょう", "今日", "today", "kyō"]},
            {"terms": ["あした、あす、みょうにち", "明日", "tomorrow", "ashita, asu, myōnichi"]},
            {"terms": ["あさ", "朝", "morning", "asa"]},
            {"terms": ["けさ", "今朝", "this morning", "kesa"]},
            {"terms": ["ひる", "昼", "afternoon", "hiru"]},
            {"terms": ["ゆうがた", "夕方", "evening", "yūgata"]},
            {"terms": ["ばん", "晩", "evening", "ban"]},
            {"terms": ["よる", "夜", "evening, night", "yoru"]},
            {"terms": ["ようび", "曜日", "~day", "yōbi"]},
            {"terms": ["しゅう", "週", "week", "shū"]},
            {"terms": ["せんしゅう", "先週", "last week", "senshū"]},
            {"terms": ["こんしゅう", "今週", "this week", "konshū"]},
            {"terms": ["らいしゅう", "来週", "next week", "raishū"]},
            {"terms": ["いっしゅうかん", "一週間", "one week", "isshūkan"]}
        ],
    
        [
            {"terms": ["にちようび", "日曜日", "Sunday", "nichi-yōbi"]},
            {"terms": ["げつようび", "月曜日", "Monday", "getsu-yōbi"]},
            {"terms": ["かようび", "火曜日", "Tuesday", "ka-yōbi"]},
            {"terms": ["すいようび", "水曜日", "Wednesday", "sui-yōbi"]},
            {"terms": ["もくようび", "木曜日", "Thursday", "moku-yōbi"]},
            {"terms": ["きんようび", "金曜日", "Friday", "kin-yōbi"]},
            {"terms": ["どようび", "土曜日", "Saturday", "do-yōbi"]}
        ],
    
        [
            {"terms": ["たいよう", "太陽", "sun", "taiyō"]},
            {"terms": ["つき", "月", "moon", "tsuki"]},
            {"terms": ["ほし", "星", "star", "hoshi"]},
            {"terms": ["てんき", "天気", "weather", "tenki"]},
            {"terms": ["はれ", "晴れ", "clear weather", "hare"]},
            {"terms": ["あめ", "雨", "rain", "ame"]},
            {"terms": ["くもり", "曇り", "cloudy", "kumori"]},
            {"terms": ["ゆき", "雪", "snow", "yuki"]},
            {"terms": ["かぜ", "風", "wind", "kaze"]},
            {"terms": ["かみなり", "雷", "thunder, lightning", "kaminari"]},
            {"terms": ["たいふう", "台風", "typhoon", "taifū"]},
            {"terms": ["あらし", "嵐", "storm", "arashi"]},
            {"terms": ["そら", "空", "sky", "sora"]}
        ],
    
        [
            {"terms": ["きた", "北", "north", "kita"]},
            {"terms": ["ひがし", "東", "east", "higashi"]},
            {"terms": ["みなみ", "南", "south", "minami"]},
            {"terms": ["にし", "西", "west", "nishi"]},
            {"terms": ["ここ", "ここ", "here", "koko"]},
            {"terms": ["そこ", "そこ", "there", "soko"]},
            {"terms": ["あそこ", "あそこ", "over there", "asoko"]},
            {"terms": ["みぎ", "右", "right", "migi"]},
            {"terms": ["ひだり", "左", "left", "hidari"]},
            {"terms": ["うえ", "上", "above, up", "ue"]},
            {"terms": ["した", "下", "below, down", "shita"]},
            {"terms": ["まえ", "前", "front", "mae"]},
            {"terms": ["うしろ", "後", "behind", "ushiro"]},
            {"terms": ["むこう", "向こう", "the other side, opposite side", "mukō"]},
            {"terms": ["ななめ", "斜め", "diagonal", "naname"]},
            {"terms": ["てまえ", "手前", "nearer, more in front", "temae"]},
            {"terms": ["とおい", "遠い", "far", "tooi"]},
            {"terms": ["ちかい", "近い", "near, close", "chikai"]}
        ],
    
        [
            {"terms": ["みず", "水", "water", "mizu"]},
            {"terms": ["ゆ", "湯", "hot water", "yu"]},
            {"terms": ["こおり", "氷", "ice", "kōri"]},
            {"terms": ["ゆげ", "湯気", "steam", "yuge"]},
            {"terms": ["ひ", "火", "fire", "hi"]},
            {"terms": ["ガス", "ガス", "gas", "gasu"]},
            {"terms": ["くうき", "空気", "air, atmosphere", "kūki"]},
            {"terms": ["つち", "土", "earth, ground", "tsuchi"]},
            {"terms": ["きんぞく", "金属", "metal, metallic", "kinzoku"]},
            {"terms": ["どろ", "泥", "mud, mire", "doro"]},
            {"terms": ["けむり", "煙", "smoke", "kemuri"]},
            {"terms": ["てつ", "鉄", "iron [Fe]", "tetsu"]},
            {"terms": ["どう", "銅", "copper [Cu]", "dō"]},
            {"terms": ["きん", "金", "gold [Au]; money", "kin"]},
            {"terms": ["ぎん", "銀", "silver [Ag]; wealth", "gin"]},
            {"terms": ["なまり", "鉛", "lead [Pb]", "namari"]},
            {"terms": ["しお", "塩", "salt [NaCl]", "shio"]}
        ],
    
        [
            {"terms": ["メートル","メートル", "meter", "mētoru"]},
            {"terms": ["リットル","リットル", "litre", "rittoru"]},
            {"terms": ["グラム","グラム", "gram", "guramu"]},
            {"terms": ["キロ","キロ", "kilo-", "kiro"]},
            {"terms": ["ミリ","ミリ", "milli-", "miri"]},
            {"terms": ["センチメートル、センチ","センチメートル、センチ", "centimeter", "senchimētoru, senchi"]},
            {"terms": ["インチ","インチ", "inch", "inchi"]}
        ],
    
        [
            {"terms": ["しゃかい", "社会", "society", "shakai"]},
            {"terms": ["けいざい", "経済", "economy, economics", "keizai"]},
            {"terms": ["かいしゃ", "会社", "company", "kaisha"]},
            {"terms": ["かいぎ", "会議", "meeting", "kaigi"]},
            {"terms": ["がっこう", "学校", "school", "gakkō"]},
            {"terms": ["やくしょ", "役所", "local government office", "yakusho"]},
            {"terms": ["みせ", "店", "store", "mise"]},
            {"terms": ["ホテル", "ホテル", "hotel", "hoteru"]},
            {"terms": ["こうじょう", "工場", "factory", "kōjō"]},
            {"terms": ["かね", "金", "money", "kane (most commonly o-kane)"]},
            {"terms": ["さつ", "札", "bill [e.g. a thousand-yen bill]", "satsu"]},
            {"terms": ["こぜに", "小銭", "small change", "kozeni"]},
            {"terms": ["つりせん", "釣り銭", "change", "tsurisen"]},
            {"terms": ["おつり", "お釣り", "change", "otsuri"]},
            {"terms": ["じどうはんばいき", "自動販売機", "vending machine", "jidōhanbaiki"]},
            {"terms": ["きっぷ", "切符", "ticket", "kippu"]},
            {"terms": ["きって", "切手", "stamp", "kitte"]}
        ],
    
        [
            {"terms": ["つくえ", "机", "desk", "tsukue"]},
            {"terms": ["いす", "椅子", "chair, position", "isu"]},
            {"terms": ["たたみ", "畳", "a tatami mat", "tatami"]},
            {"terms": ["と", "戸", "door", "to"]},
            {"terms": ["とびら", "扉", "door panel", "tobira"]},
            {"terms": ["ドア", "ドア", "door", "doa"]},
            {"terms": ["まど", "窓", "window", "mado"]},
            {"terms": ["ふとん", "布団", "futon", "futon"]},
            {"terms": ["げんかん", "玄関", "entrance", "genkan"]},
            {"terms": ["いえ", "家", "house, home", "ie"]},
            {"terms": ["エレベーター", "エレベーター", "elevator", "erebētā"]},
            {"terms": ["エスカレーター", "エスカレーター", "escalator", "esukarētā"]},
            {"terms": ["でんき", "電気", "electricity", "denki"]}
        ],
    
        [
            {"terms": ["くぎ", "釘", "nail, spike", "kugi"]},
            {"terms": ["ひも", "紐", "string, cord", "himo"]},
            {"terms": ["なわ", "縄", "rope, string", "nawa"]},
            {"terms": ["ふくろ", "袋", "pocket, bag", "fukuro"]},
            {"terms": ["かばん", "鞄", "leather bag", "kaban"]},
            {"terms": ["かさ", "傘", "umbrella, parasol", "kasa"]},
            {"terms": ["かぎ", "鍵", "key", "kagi"]},
            {"terms": ["ちょうこく", "彫刻", "sculpture, engraving", "chōkoku"]}
        ],
    
        [
            {"terms": ["ぶんぼうぐ", "文房具", "quill", "bunbōgu"]},
            {"terms": ["インク", "インク", "ink", "inku"]},
            {"terms": ["ペン", "ペン", "pen", "pen"]},
            {"terms": ["ボールペン", "ボールペン", "ball-point pen", "bōrupen"]},
            {"terms": ["まんねんひつ", "万年筆", "fountain pen", "mannenhitsu"]},
            {"terms": ["えんぴつ", "鉛筆", "pencil", "enpitsu"]},
            {"terms": ["ふで", "筆", "brush for writing or painting", "fude"]},
            {"terms": ["チョーク", "チョーク", "chalk", "chōku"]},
            {"terms": ["けしゴム", "消しゴム", "eraser", "keshigomu"]},
            {"terms": ["えんぴつけずり", "鉛筆削り", "pencil sharpener", "enpitsu-kezuri"]},
            {"terms": ["じょうぎ", "定規", "ruler", "jōgi"]},
            {"terms": ["ノート", "ノート", "notebook", "nōto"]},
            {"terms": ["にっき", "日記", "diary", "nikki"]},
            {"terms": ["カバー", "カバー", "book cover", "kabā"]},
            {"terms": ["ふうとう", "封筒", "envelope", "fūtō"]},
            {"terms": ["はさみ", "鋏", "scissors", "hasami"]},
            {"terms": ["ホッチキス", "ホッチキス", "stapler", "hotchikisu"]}
        ],
    
        [
            {"terms": ["ふく", "服", "clothes", "fuku"]},
            {"terms": ["ようふく", "洋服", "western clothing", "yōfuku"]},
            {"terms": ["きもの", "着物", "kimono", "kimono"]},
            {"terms": ["わふく", "和服", "Japanese clothing", "wafuku"]},
            {"terms": ["そで", "袖", "sleeve", "sode"]},
            {"terms": ["えり", "襟", "lapel, collar", "eri"]},
            {"terms": ["ボタン", "ボタン", "button", "botan"]},
            {"terms": ["チャック", "チャック", "zipper, fastener", "chakku"]},
            {"terms": ["ジッパー", "ジッパー", "zipper, fastener", "jippā"]},
            {"terms": ["ファスナー", "ファスナー", "zipper, fastener", "fasunā"]},
            {"terms": ["ベルト", "ベルト", "belt", "beruto"]},
            {"terms": ["くつ", "靴", "shoe", "kutsu"]},
            {"terms": ["くつした", "靴下", "sock", "kutsushita"]},
            {"terms": ["めがね", "眼鏡", "glasses", "megane"]}
        ],
    
        [
            {"terms": ["てつどう", "鉄道", "railway", "tetsudō"]},
            {"terms": ["えき", "駅", "station", "eki"]},
            {"terms": ["ひこうき", "飛行機", "airplane", "hikōki"]},
            {"terms": ["くうこう", "空港", "airport", "kūkō"]},
            {"terms": ["ひこうじょう", "飛行場", "airfield; airport", "hikōjō"]},
            {"terms": ["みち", "道", "street, way, road", "michi"]},
            {"terms": ["どうろ", "道路", "road", "dōro"]},
            {"terms": ["バスてい", "バス停", "bus-stop", "basutei"]},
            {"terms": ["とおり", "通り", "avenue", "tōri"]},
            {"terms": ["でんしゃ", "電車", "train", "densha"]},
            {"terms": ["くるま", "車", "car", "kuruma"]},
            {"terms": ["じどうしゃ", "自動車", "car", "jidōsha"]}
        ],
    
        [
            {"terms": ["もじ", "文字", "letter, character, script", "moji"]},
            {"terms": ["じ", "字", "a letter, character", "ji"]},
            {"terms": ["かんじ", "漢字", "Chinese character", "kanji"]},
            {"terms": ["ひらがな", "平仮名", "hiragana syllabary characters", "hiragana"]},
            {"terms": ["カタカナ", "片仮名", "katakana syllabary characters", "katakana"]},
            {"terms": ["すうじ", "数字", "numbers", "sūji"]},
            {"terms": ["アルファベット", "アルファベット", "alphabet", "arufabetto"]},
            {"terms": ["ローマ字", "", "Roman characters, latin script", "rōmaji"]},
            {"terms": ["がいこくご", "外国語", "foreign language", "gaikokugo"]},
            {"terms": ["にほんご", "日本語", "Japanese [language]", "nihongo"]},
            {"terms": ["こくご", "国語", "national language", "kokugo"]},
            {"terms": ["えいご", "英語", "English [language]", "eigo"]},
            {"terms": ["ちゅうごくご", "中国語", "Chinese [language]", "chūgokugo"]},
            {"terms": ["どいつご", "ドイツ語", "German [language]", "doitsugo"]},
            {"terms": ["すぺいんご", "スペイン語", "Spanish [language]", "supeingo"]},
            {"terms": ["ふらんすご", "フランス語", "French [language]", "furansugo"]},
            {"terms": ["ちょうせんご", "朝鮮語", "Korean [language]", "chōsengo"]},
            {"terms": ["かんこくご", "韓国語", "South Korean [language]", "kankokugo"]}
        ],
    
        [
            {"terms": ["ほん", "本", "book", "hon"]},
            {"terms": ["かみ", "紙", "paper", "kami"]},
            {"terms": ["てがみ", "手紙", "letter", "tegami"]},
            {"terms": ["しんぶん", "新聞", "newspaper", "shinbun"]},
            {"terms": ["じしょ", "辞書", "dictionary", "jisho"]},
            {"terms": ["パソコン", "パソコン", "personal computer", "pasokon"]}
        ],
    
        [
            {"terms": ["いろ", "色", "color", "iro, shikisai"]},
            {"terms": ["あか", "赤", "red", "aka"]},
            {"terms": ["きいろ", "黄色", "yellow", "kiiro"]},
            {"terms": ["みどり", "緑", "green", "midori"]},
            {"terms": ["あお", "青", "blue", "ao"]},
            {"terms": ["むらさき", "紫", "purple", "murasaki, murasakiiro"]},
            {"terms": ["しろ", "白", "white", "shiro"]},
            {"terms": ["くろ", "黒", "black", "kuro"]},
            {"terms": ["ピンク", "ピンク", "pink", "pinku"]},
            {"terms": ["ちゃいろ", "茶色", "brown", "chairo"]},
            {"terms": ["はいいろ", "灰色", "grey", "haiiro"]},
            {"terms": ["ねずみいろ", "鼠色", "grey", "nezumiiro"]},
            {"terms": ["オレンジ", "オレンジ", "orange", "orenji"]}
        ],
    
        [
            {"terms": ["え", "絵", "picture", "e"]},
            {"terms": ["おんがく", "音楽", "music", "ongaku"]},
            {"terms": ["りか", "理科", "science", "rika"]},
            {"terms": ["さんすう", "算数", "arithmetic", "sansū"]},
            {"terms": ["れきし", "歴史", "history", "rekishi"]},
            {"terms": ["ちり", "地理", "geography", "chiri"]},
            {"terms": ["たいいく", "体育", "physical education", "taiiku"]},
            {"terms": ["スポーツ", "スポーツ", "sport", "supōtsu"]},
            {"terms": ["システム", "システム", "system", "shisutemu"]},
            {"terms": ["じょうほう", "情報", "information, news", "jōhō"]},
            {"terms": ["ひつよう", "必要", "necessity", "hitsuyō"]},
            {"terms": ["べんきょう", "勉強", "study", "benkyō"]},
            {"terms": ["いらい", "依頼", "request", "irai"]}
        ],
    
        [
            {"terms": ["れい", "零", "zero", "rei"]},
            {"terms": ["ゼロ", "ゼロ", "zero", "zero"]},
            {"terms": ["いち", "一", "one", "ichi"]},
            {"terms": ["に", "二", "two", "ni"]},
            {"terms": ["さん", "三", "three", "san"]},
            {"terms": ["よん、し", "四", "four", "yon, shi"]},
            {"terms": ["ご", "五", "five", "go"]},
            {"terms": ["ろく", "六", "six", "roku"]},
            {"terms": ["なな、しち", "七", "seven", "nana, shichi"]},
            {"terms": ["はち", "八", "eight", "hachi"]},
            {"terms": ["きゅう、く", "九", "nine", "kyū, ku"]},
            {"terms": ["じゅう", "十", "ten", "jū"]},
            {"terms": ["ひゃく", "百", "hundred", "hyaku"]},
            {"terms": ["せん", "千", "thousand", "sen"]},
            {"terms": ["まん", "万", "ten thousand", "man"]},
            {"terms": ["おく", "億", "one hundred million", "oku"]},
            {"terms": ["ひとつ", "一つ", "one, one thing", "hitotsu"]},
            {"terms": ["ふたつ", "二つ", "two, two things", "futatsu"]},
            {"terms": ["みっつ", "三つ", "three, three things", "mittsu"]},
            {"terms": ["よっつ", "四つ", "four, four things", "yottsu"]},
            {"terms": ["いつつ", "五つ", "five, five things", "itsutsu"]},
            {"terms": ["むっつ", "六つ", "six, six things", "muttsu"]},
            {"terms": ["ななつ", "七つ", "seven, seven things", "nanatsu"]},
            {"terms": ["やっつ", "八つ", "eight, eight things", "yattsu"]},
            {"terms": ["ここのつ", "九つ", "nine, nine things", "kokonotsu"]},
            {"terms": ["とお", "十", "ten, ten things", "tō"]}
        ],
    
        [
            {"terms": ["これ", "これ", "this", "kore"]},
            {"terms": ["それ", "それ", "that", "sore"]},
            {"terms": ["あれ", "あれ", "that over there", "are"]},
            {"terms": ["どれ", "どれ", "which", "dore"]},
            {"terms": ["こちら、こっち", "こちら、こっち", "this direction, thing, person, or place", "kochira, kocchi"]},
            {"terms": ["そちら、そっち", "そちら、そっち", "that direction, thing, person, or place", "sochira, socchi"]},
            {"terms": ["あちら、あっち", "あちら、あっち", "that direction, thing, person, or place", "achira, acchi"]},
            {"terms": ["どちら、どっち", "どちら、どっち", "which direction, thing, person, or place", "dochira, docchi"]},
            {"terms": ["ひみつ", "秘密", "secret", "himitsu"]},
            {"terms": ["じどう", "自動", "automatic", "jidō"]},
            {"terms": ["ないよう", "内容", "content", "naiyō"]},
            {"terms": ["はば", "幅", "hem, piece, strip", "haba"]},
            {"terms": ["せいしき", "正式", "formality", "seishiki"]},
            {"terms": ["けっこん", "結婚", "marriage", "kekkon"]},
            {"terms": ["げんざい", "現在", "now", "genzai"]},
            {"terms": ["いま", "今", "now", "ima"]},
            {"terms": ["かこ", "過去", "past", "kako"]},
            {"terms": ["みらい", "未来", "future", "mirai"]}
        ],
    
        [
            {"terms": ["いい、よい", "良い", "good", "ii, yoi"]},
            {"terms": ["すごい", "凄い", "amazing", "sugoi"]},
            {"terms": ["すばらしい", "素晴らしい", "wonderful", "subarashii"]},
            {"terms": ["わるい", "悪い", "bad, inferior", "warui"]},
            {"terms": ["たかい", "高い", "expensive, high", "takai"]},
            {"terms": ["ひくい", "低い", "low", "hikui"]},
            {"terms": ["やすい", "安い", "cheap", "yasui"]},
            {"terms": ["おおきい", "大きい", "big", "ōkii"]},
            {"terms": ["ちいさい", "小さい", "small", "chiisai"]},
            {"terms": ["ほそい", "細い", "thin", "hosoi"]},
            {"terms": ["ふとい", "太い", "thick", "futoi"]},
            {"terms": ["ふるい", "古い", "old", "furui"]},
            {"terms": ["あたらしい", "新しい", "new", "atarashii"]},
            {"terms": ["わかい", "若い", "young", "wakai"]},
            {"terms": ["かるい", "軽い", "light, easy", "karui"]},
            {"terms": ["おもい", "重い", "heavy", "omoi"]},
            {"terms": ["やさしい", "易しい", "easy, simple", "yasashii"]},
            {"terms": ["むずかしい", "難しい", "difficult", "muzukashii"]},
            {"terms": ["やわらかい", "柔らかい", "soft", "yawarakai"]},
            {"terms": ["かたい", "硬い、堅い", "hard", "katai"]},
            {"terms": ["あつい", "熱い、暑い", "hot", "atsui"]},
            {"terms": ["つめたい", "冷たい", "cold", "tsumetai"]},
            {"terms": ["さむい", "寒い", "cold", "samui"]},
            {"terms": ["おいしい", "美味しい", "delicious", "oishii"]},
            {"terms": ["うまい", "美味い、旨い", "delicious", "appetizing, umai"]},
            {"terms": ["まずい", "不味い", "tastes awful", "mazui"]},
            {"terms": ["あまい", "甘い", "sweet", "amai"]},
            {"terms": ["からい", "辛い", "hot [spicy]", "karai"]},
            {"terms": ["しょっぱい", "塩っぱい", "salty", "shoppai"]},
            {"terms": ["にがい", "苦い", "bitter", "nigai"]},
            {"terms": ["うつくしい", "美しい", "beautiful", "utsukushii"]}
        ],
    
        [
            {"terms": ["うれしい", "嬉しい", "happy", "ureshii"]},
            {"terms": ["たのしい", "楽しい", "fun", "tanoshii"]},
            {"terms": ["かなしい", "悲しい", "sad", "kanashii"]},
            {"terms": ["さびしい", "寂しい、淋しい", "lonely", "sabishii"]},
            {"terms": ["さみしい", "寂しい、淋しい", "lonely", "samishii"]},
            {"terms": ["こわい", "怖い、恐い", "scary", "kowai"]},
            {"terms": ["いたい", "痛い", "painful", "itai"]},
            {"terms": ["かゆい", "痒い", "itchy", "kayui"]},
            {"terms": ["くさい", "臭い", "stinky", "kusai"]},
            {"terms": ["つらい", "辛い", "painful, heart-breaking", "tsurai"]}
        ],
    
        [
            {"terms": ["する","する", "to do", "suru"]},
            {"terms": ["やる","やる", "to do", "yaru"]},
            {"terms": ["いる", "いる", "to exist [for animate objects]", "iru"]},
            {"terms": ["ある", "ある", "to exist [for inanimate objects]", "aru"]},
            {"terms": ["なる", "なる", "to become", "naru"]},
            {"terms": ["おこる", "起こる", "to occur", "okoru"]},
            {"terms": ["おこる", "興る", "to rise, to flourish", "okoru"]},
            {"terms": ["あらわれる", "現れる", "to appear", "arawareru"]},
            {"terms": ["いきる", "生きる", "to live", "ikiru"]},
            {"terms": ["うむ", "生む、産む", "to give birth", "umu"]},
            {"terms": ["しぬ", "死ぬ", "to die", "shinu"]},
            {"terms": ["こわれる", "壊れる", "to break", "kowareru"]},
            {"terms": ["いく", "行く", "to go", "iku"]},
            {"terms": ["くる", "来る", "to come", "kuru"]},
            {"terms": ["かえる", "帰る", "to return, to come home, to go home", "kaeru"]},
            {"terms": ["かえる", "返る", "to return, to come back, to go back", "kaeru"]},
            {"terms": ["あるく", "歩く", "to walk", "aruku"]},
            {"terms": ["とぶ", "飛ぶ", "to jump, to fly", "tobu"]},
            {"terms": ["およぐ", "泳ぐ", "to swim", "oyogu"]}
        ],
    
        [
            {"terms": ["うごく", "動く", "to movein", "ugoku"]},
            {"terms": ["おどる", "踊る", "to dance", "odoru"]},
            {"terms": ["ねる", "寝る", "to sleep", "neru"]},
            {"terms": ["うたう", "歌う", "to sing", "utau"]},
            {"terms": ["かむ", "噛む", "to bite", "kamu"]},
            {"terms": ["たべる", "食べる", "to eat", "taberu"]},
            {"terms": ["のむ", "飲む", "to drink", "nomu"]},
            {"terms": ["さわる", "触る", "to touch", "sawaru"]},
            {"terms": ["なげる", "投げる", "to throw", "nageru"]},
            {"terms": ["もつ", "持つ", "to hold", "motsu"]},
            {"terms": ["うつ", "打つ", "to hit, to strike", "utsu"]},
            {"terms": ["なぐる", "殴る", "to hit, to strike", "naguru"]},
            {"terms": ["さす", "指す", "to point", "sasu"]},
            {"terms": ["さす", "刺す", "to stab", "sasu"]},
            {"terms": ["さす", "差す", "to raise or extend one's hands", "sasu"]},
            {"terms": ["ける", "蹴る", "to kick", "keru"]},
            {"terms": ["すわる", "座る", "to sit", "suwaru"]},
            {"terms": ["たつ", "立つ", "to stand", "tatsu"]},
            {"terms": ["はしる", "走る", "to run", "hashiru"]},
            {"terms": ["あく", "空く", "to become unoccupied", "aku"]},
            {"terms": ["こむ", "込む", "to be crowded", "komu"]},
            {"terms": ["いる", "要る", "to need", "iru"]},
            {"terms": ["かわく", "乾く", "to become dry", "kawaku"]}
        ],
    
        [
            {"terms": ["みだす", "乱す", "to disarrange, to disturb", "midasu"]},
            {"terms": ["みだれる", "乱れる", "to become confused, to be disturbed", "midareru"]},
            {"terms": ["つかえる", "仕える", "to work for, to serve", "tsukaeru"]},
            {"terms": ["そなわる", "備わる", "to be furnished with", "sonawaru"]},
            {"terms": ["すぐれる", "優れる", "to surpass, to excel", "sugureru"]},
            {"terms": ["ひえる", "冷える", "to get chilly, to grow cold, to cool down", "hieru"]},
            {"terms": ["さめる", "覚める", "to become sober, to wake, to be disillusioned", "sameru"]},
            {"terms": ["さめる", "冷める", "to cool down", "sameru"]},
            {"terms": ["むく", "向く", "to turn toward, to face", "muku"]},
            {"terms": ["たおれる", "倒れる", "to collapse, to fall", "taoreru"]},
            {"terms": ["かたまる", "固まる", "to solidify, to become firm, to harden", "katamaru"]},
            {"terms": ["うまる", "埋まる", "to be surrounded, to overflow, to be filled", "umaru"]},
            {"terms": ["うもれる", "埋もれる", "to be covered, to be buried", "umoreru"]},
            {"terms": ["ます", "増す", "to grow, to increase", "masu"]},
            {"terms": ["ふえる", "増える", "to multiply, to increase", "fueru"]},
            {"terms": ["へる", "減る", "to decrease", "heru"]},
            {"terms": ["はずれる", "外れる", "to deviate", "hazureru"]},
            {"terms": ["ふとる", "太る", "to grow fat", "futoru"]},
            {"terms": ["はじまる", "始まる", "to begin", "hajimaru"]},
            {"terms": ["おわる", "終わる", "to close, to finish", "owaru"]},
            {"terms": ["きめる", "決める", "to decide", "kimeru"]}
        ],
    
        [
            {"terms": ["みる", "見る", "to see", "miru"]},
            {"terms": ["きく", "聞く、聴く", "to hear, to listen", "kiku"]},
            {"terms": ["さわる", "触る", "to touch, to feel", "sawaru"]},
            {"terms": ["かぐ", "嗅ぐ", "to smell", "kagu"]},
            {"terms": ["いう", "言う", "to say", "iu"]},
            {"terms": ["はなす", "話す", "to speak", "hanasu"]},
            {"terms": ["かたる", "語る", "to tell", "kataru"]},
            {"terms": ["かく", "書く", "to write", "kaku"]},
            {"terms": ["よむ", "読む", "to read", "yomu"]},
            {"terms": ["つかう", "使う", "to use", "tsukau"]},
            {"terms": ["つくる", "作る、造る、創る", "to make", "tsukuru"]},
            {"terms": ["なおす", "直す、治す", "to fix, repair", "naosu"]},
            {"terms": ["すてる", "捨てる", "to discard, throw away", "suteru"]},
            {"terms": ["とる", "取る、撮る、採る", "to take", "toru"]},
            {"terms": ["おく", "置く", "to put", "oku"]}
        ],
    
        [
            {"terms": ["かなしむ", "悲しむ、哀しむ", "to be sad", "kanashimu"]},
            {"terms": ["なく", "泣く", "to cry", "naku"]},
            {"terms": ["わらう", "笑う", "to laugh", "warau"]},
            {"terms": ["おこる", "怒る", "to be angry", "okoru"]},
            {"terms": ["ほめる", "褒める", "to encourage", "homeru"]},
            {"terms": ["しかる", "叱る", "to scold", "shikaru"]},
            {"terms": ["よろこぶ", "喜ぶ", "to celebrate, to have delight, to have joy", "yorokobu"]},
            {"terms": ["よろこび", "喜び", "joy, delight", "yorokobi"]},
            {"terms": ["なぐさめる", "慰める", "to console, to consolate, to provide empathy", "nagusameru"]},
            {"terms": ["あきる", "飽きる", "to be disinterested, to be bored, to be tired of", "akiru"]},
            {"terms": ["おどろく", "驚く", "to be astonished, to be surprised, to be scared", "odoroku"]}
        ],
    
        [
            {"terms": ["あう", "会う", "to meet, to interview", "au"]},
            {"terms": ["あける", "開ける", "to open, to unwrap", "akeru"]},
            {"terms": ["あそぶ", "遊ぶ", "to play", "asobu"]},
            {"terms": ["あつまる", "集まる", "to gatherin", "atsumaru"]},
            {"terms": ["うる", "売る", "to sell", "uru"]},
            {"terms": ["える", "得る", "to obtain [some benefit or knowledge]", "eru"]},
            {"terms": ["おる", "折る", "to break, to fold", "oru"]},
            {"terms": ["かう", "買う", "to buy", "kau"]},
            {"terms": ["きる", "切る", "to cut", "kiru"]},
            {"terms": ["きる", "着る", "to wear [on the upper body]", "kiru"]},
            {"terms": ["はく", "履く", "to wear [on the lower body]", "haku"]},
            {"terms": ["かえる", "変える", "to change", "kaeru"]},
            {"terms": ["かえる", "代える", "to exchange, to substitute, to replace", "kaeru"]},
            {"terms": ["しめる", "閉める", "to close", "shimeru"]},
            {"terms": ["しめる", "締める", "to tie, to fasten", "shimeru"]},
            {"terms": ["しめる", "占める", "to comprise, to account for", "shimeru"]},
            {"terms": ["しる", "知る", "to know", "shiru"]},
            {"terms": ["つかれる", "疲れる", "to get tired", "tsukareru"]},
            {"terms": ["でかける", "出掛ける", "to go out, to depart", "dekakeru"]},
            {"terms": ["はたらく", "働く", "to work [e.g. at a job]", "hataraku"]},
            {"terms": ["はなす", "放す、離す", "to let go of", "hanasu"]},
            {"terms": ["やすむ", "休む", "to rest, to take a break, to go to bed", "yasumu"]},
            {"terms": ["わかれる", "分かれる", "to split into, to be divided", "wakareru"]},
            {"terms": ["わかれる", "別れる", "to part, to separate, to break up", "wakareru"]}
        ],
    
        [
            {"terms": ["もう","もう", "already", "mō"]},
            {"terms": ["まだ","まだ", "still, yet", "mada"]},
            {"terms": ["ずっと","ずっと", "always", "zutto"]},
            {"terms": ["とても","とても", "very", "totemo"]},
            {"terms": ["こう","こう", "like this", "kō"]},
            {"terms": ["そう","そう", "like that", "sō"]},
            {"terms": ["ああ","ああ", "Oh!, Ah!", "ā"]},
            {"terms": ["どう","どう", "how", "dō"]},
            {"terms": ["しばしば","しばしば", "often", "shibashiba"]}
        ],
    
        [
            {"terms": ["この", "this", "kono"]},
            {"terms": ["その","その", "that", "sono"]},
            {"terms": ["あの","あの", "that", "ano"]},
            {"terms": ["どの","どの", "which", "dono"]},
            {"terms": ["はい","はい", "yes", "hai"]},
            {"terms": ["いいえ","いいえ", "no", "iie"]},
            {"terms": ["でも","でも", "but", "demo"]},
            {"terms": ["しかし","しかし", "but, however", "shikashi"]},
            {"terms": ["そして","そして", "and then, and, thus, and now", "soshite"]},
            {"terms": ["それに","それに", "besides", "soreni"]},
            {"terms": ["なぜなら","なぜなら", "that is because, being because", "nazenara"]}
        ],
    
        [
            {"terms": ["が","が", "subject marker, but", "ga"]},
            {"terms": ["で","で", "at, by", "de"]},
            {"terms": ["と","と", "and, with", "to"]},
            {"terms": ["に","に", "indirect object marker", "ni"]},
            {"terms": ["の","の", "possession marker, of", "no"]},
            {"terms": ["へ","へ", "to", "e (へ is read as e when a particle)"]},
            {"terms": ["まで","まで", "to", "made"]},
            {"terms": ["から","から", "from", "kara"]},
            {"terms": ["より","より", "than", "yori"]},
            {"terms": ["を","を", "direct object marker", "o"]}
        ],
    
        [
            {"terms": ["および", "及び", "and; as well as", "oyobi"]},
            {"terms": ["か", "か", "whether", "ka"]},
            {"terms": ["かも", "かも", "might be, possible that", "kamo"]},
            {"terms": ["そして", "そして", "and then", "soshite"]},
            {"terms": ["それとも", "それとも", "or", "soretomo"]},
            {"terms": ["だの", "だの", "things like..., including, such things as", "dano"]},
            {"terms": ["つつ", "つつ", "ongoing occurrence", "tsutsu"]},
            {"terms": ["て", "て", "te form of verb or adjective [see explanation]","te"]},
            {"terms": ["と", "と", "if, when, that", "to"]},
            {"terms": ["ながら", "ながら", "while, though, both", "nagara"]},
            {"terms": ["ならびに", "ならびに", "as well as", "narabini"]}
        ],
    
        [
            {"terms": ["なり", "なり", "whether or not", "nari"]},
            {"terms": ["に", "に", "to <somewhere>, by <someone>", "ni"]},
            {"terms": ["の", "の", "possession", "no"]},
            {"terms": ["ので", "ので", "so", "node"]},
            {"terms": ["また", "又", "also, again", "mata"]},
            {"terms": ["または", "又は", "or alternatively", "matawa"]},
            {"terms": ["も", "も", "also, too", "mo"]},
            {"terms": ["や", "や", "and", "ya"]}
        ],
    
        [
            {"terms": ["ね","ね", "emphasis and question marker equivalent to 'right?'", "ne"]},
            {"terms": ["か","か",  "question marker", "ka"]},
            {"terms": ["な","な", "the copula particle used after quasi-adjectives", "na"]},
            {"terms": ["かしら","かしら", "I wonder", "kashira"]},
            {"terms": ["さ", "さ","-ness", "sa"]},
            {"terms": ["っけ", "っけ","particle indicating that the speaker is trying to recall some information", "-kke"]}
        ],
    
        [
            {"terms": ["こそ","こそ", "emphasis", "koso"]},
            {"terms": ["さえ","さえ", "even", "sae"]},
            {"terms": ["しか","しか", "only", "shika"]},
            {"terms": ["すら","すら", "even", "sura"]},
            {"terms": ["くらい、ぐらい", "くらい、ぐらい", "approximately, about", "kurai"]},
            {"terms": ["だけ","だけ", "only, as much as", "dake"]},
            {"terms": ["だって","だって", "however", "datte"]},
            {"terms": ["ったら","ったら", "casual topic marker", "ttara"]},
            {"terms": ["って","って", "said that", "tte"]},
            {"terms": ["でも","でも", "also, or", "demo"]},
            {"terms": ["など","など", "for example", "nado"]},
            {"terms": ["なら","なら", "if [for verbs]; subject marker [for nouns]", "nara"]},
            {"terms": ["なんか","なんか", "casual undervalue, dislike, lack", "nanka"]},
            {"terms": ["なんて","なんて", "casual undervalue, dislike, lack", "nante"]},
            {"terms": ["まで","まで", "until", "made"]},
            {"terms": ["も", "も","too, also", "mo"]}
        ]
    ]
    // topics:[
    //     [
    //         {terms:["ENG1-1","GER1-1"]},
    //         {terms:["ENG1-2","GER1-2"]},
    //         {terms:["ENG1-3","GER1-3"]},
    //         {terms:["ENG1-4","GER1-4"]},
    //     ],
    //     [
    //         {terms:["ENG2-1","GER2-1"]},
    //         {terms:["ENG2-2","GER2-2"]},
    //         {terms:["ENG2-3","GER2-3"]},
    //         {terms:["ENG2-4","GER2-4"]},
    //     ]
    // ]
} as VocabDataDef
